EXPERIMENT:
  NAME: ""
  TAG: "kd,res50,mobilenetv1"
  PROJECT: "proj_cub_200_2011"
DATASET:
  TYPE: "cub_200_2011"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 8
DISTILLER:
  TYPE: "KD"
  TEACHER: "ResNet50"
  STUDENT: "MobileNetV2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
KD:
  TEMPERATURE: 1
  LOSS:
    CE_WEIGHT: 0.5
    KD_WEIGHT: 0.5
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
