EXPERIMENT:
  NAME: ""
  TAG: "dkd,res32x4,res8x4"
  PROJECT: "proj_cub_200_2011"
DATASET:
  TYPE: "cub_200_2011"
  NUM_WORKERS: 16
DISTILLER:
  TYPE: "DKD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 8
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

