EXPERIMENT:
  NAME: ""
  TAG: "kd,dot,r18,mv2"
  PROJECT: "proj_cub_200_2011"
DATASET:
  TYPE: "cub_200_2011"
  NUM_WORKERS: 16
DISTILLER:
  TYPE: "KD"
  TEACHER: "ResNet18"
  STUDENT: "MobileNetV1"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

